# Generated by Django 4.1.2 on 2022-11-13 11:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='album',
            options={'ordering': ('pk',)},
        ),
        migrations.AddField(
            model_name='profile',
            name='n',
            field=models.CharField(blank=True, max_length=30),
        ),
    ]
