# Generated by Django 4.1.2 on 2022-11-13 11:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0003_profile_s'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='s',
            field=models.CharField(max_length=30),
        ),
    ]
