# Generated by Django 4.1.2 on 2022-11-13 11:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0004_alter_profile_s'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='s',
        ),
    ]
