# Generated by Django 4.1.3 on 2022-12-01 14:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='appuser',
            name='personal_photo',
            field=models.ImageField(blank=True, upload_to='pet_photos'),
        ),
    ]
