# Generated by Django 4.1.3 on 2022-12-02 15:18

import django.core.validators
from django.db import migrations, models
import petstagram_from_zero.core.validators


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_alter_appuser_gender'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appuser',
            name='first_name',
            field=models.CharField(blank=True, max_length=30, validators=[django.core.validators.MinLengthValidator(2), petstagram_from_zero.core.validators.validate_only_letters]),
        ),
        migrations.AlterField(
            model_name='appuser',
            name='last_name',
            field=models.CharField(blank=True, max_length=30, validators=[django.core.validators.MinLengthValidator(2), petstagram_from_zero.core.validators.validate_only_letters]),
        ),
    ]
