# Generated by Django 4.1.3 on 2022-12-03 11:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_alter_appuser_first_name_alter_appuser_last_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appuser',
            name='personal_photo',
            field=models.ImageField(blank=True, upload_to='users_photos'),
        ),
    ]
