# Generated by Django 4.1.3 on 2022-11-03 19:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Departments',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=15)),
                ('age', models.PositiveIntegerField()),
                ('born', models.DateField()),
                ('position', models.CharField(choices=[('default', 'default'), ('junior', 'junior'), ('senior', 'senior'), ('devops', 'devops')], default='default', max_length=7)),
                ('department', models.ForeignKey(default=3, on_delete=django.db.models.deletion.CASCADE, to='web.departments')),
            ],
        ),
    ]
