# Generated by Django 4.1.3 on 2022-11-07 10:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmployeeBasic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=30)),
                ('last_name', models.CharField(max_length=30)),
                ('seniority_level', models.CharField(choices=[('junior', 'junior'), ('regular', 'regular'), ('senior', 'senior')], max_length=30)),
            ],
        ),
        migrations.AlterModelOptions(
            name='employee',
            options={'ordering': ['id']},
        ),
        migrations.AlterField(
            model_name='employee',
            name='position',
            field=models.CharField(choices=[('default', 'default'), ('junior', 'junior'), ('devops', 'devops')], default='default', max_length=7),
        ),
    ]
