# Generated by Django 4.1.3 on 2022-11-19 20:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0003_alter_employee_position'),
    ]

    operations = [
        migrations.CreateModel(
            name='Photo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photo', models.ImageField(upload_to='pet_photos')),
            ],
            options={
                'ordering': ['-pk'],
            },
        ),
    ]
