# Generated by Django 4.1.1 on 2022-11-14 11:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='petstagramuser',
            name='profile_picture',
            field=models.URLField(blank=True),
        ),
    ]
